#!/usr/bin/env bash
#
# Agent Foundry - Agent Sessions on the Sandbox Transport
#
# The sandbox-native replacement for the SSH/scp machinery in lib/agent.sh.
#
# The whole copy-into-the-VM step is gone: the volume root is mounted, so the
# rendered start script is simply written to a host path that also exists
# inside the sandbox. Logs are likewise plain host files.
#
# Agent metadata (binaries, session names, templates, log paths) still comes
# from lib/agent-registry.sh - that layer was always transport-agnostic.
#
# Requires: lib/agent-registry.sh, lib/sandbox.sh
#

# Agent metadata registry, sourced directly so this module is self-contained.
_AGENT_SANDBOX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${_AGENT_SANDBOX_DIR}/agent-registry.sh" ]]; then
    # shellcheck source=/dev/null
    source "${_AGENT_SANDBOX_DIR}/agent-registry.sh"
fi

# ============================================================================
# HELPERS
# ============================================================================

# Directory inside the volume root for Foundry-generated runtime files.
_agent_runtime_dir() {
    printf '%s/.foundry\n' "$1"
}

# Is the agent's tmux session alive inside the sandbox?
# Usage: foundry_agent_running <box> <root> <agent> && ...
foundry_agent_running() {
    local box="$1"
    local root="$2"
    local agent="$3"

    local session
    session="$(agent_session_name "$agent")"

    sandbox_exec "$box" "$root" tmux has-session -t "$session" >/dev/null 2>&1
}

# Render the start script for an autonomous agent into the volume root.
# Prints the path (identical on host and inside the sandbox).
_agent_render_start_script() {
    local root="$1"
    local agent="$2"

    local template
    template="$(agent_start_template "$agent")"

    if [[ -z "$template" || ! -f "$template" ]]; then
        log_error "No start template for agent '$agent'"
        return 1
    fi

    local runtime_dir
    runtime_dir="$(_agent_runtime_dir "$root")"
    mkdir -p "$runtime_dir"

    local script="${runtime_dir}/start-${agent}.sh"

    {
        printf '#!/bin/bash\n'
        printf '# Auto-generated by Agent Foundry for agent: %s\n' "$agent"
        # The sandbox home, not the host path: both name the same directory,
        # and the agent should see a normal home rather than the volume root's
        # location on the host.
        printf 'export AGENT_WORKSPACE="%s"\n' "$(sandbox_home)"
        printf 'export AGENT_TYPE="%s"\n' "$agent"
        printf 'export AGENT_BINARY="%s"\n' "$(agent_binary "$agent")"
        printf 'export AGENT_SESSION_NAME="%s"\n' "$(agent_session_name "$agent")"
        printf 'export AGENT_LOG_FILE="%s"\n' "$(agent_log_file "$agent" "$root")"
        printf 'export AGENT_TASK_PROMPT_FILE="%s"\n' "$(agent_task_prompt_file "$agent" "$root")"
        printf 'export AGENT_MAX_ITERATIONS="%s"\n' "$(agent_max_iterations "$agent")"
        printf 'export AGENT_TIMEOUT_MINUTES="%s"\n' "$(agent_default_timeout_minutes "$agent")"
        printf 'export AGENT_THREAD_KEY="%s"\n' "${FOUNDRY_THREAD_KEY:-}"
        printf 'export AGENT_SESSION_ID="%s"\n' "${FOUNDRY_SESSION_ID:-}"
        # Goal-mode agents need the completion condition and a repository to
        # anchor on. Both are empty for every other agent type.
        printf 'export AGENT_GOAL_CONDITION=%s\n' "$(printf '%q' "${FOUNDRY_GOAL_CONDITION:-}")"
        printf 'export AGENT_REPO_PATH=%s\n' "$(printf '%q' "${FOUNDRY_REPO_PATH:-}")"
        printf 'export AGENT_GOAL_TIMEOUT=%s\n' "$(printf '%q' "${FOUNDRY_GOAL_TIMEOUT:-4h}")"
        cat "$template"
    } > "$script"

    chmod +x "$script"
    printf '%s\n' "$script"
}

# ============================================================================
# LIFECYCLE
# ============================================================================

# Start the project's agent inside its sandbox, in a tmux session.
# Idempotent: a running session is left alone.
# Usage: foundry_agent_start <project> <box> <root>
foundry_agent_start() {
    local project="$1"
    local box="$2"
    local root="$3"

    local agent
    agent="$(project_get "$project" '.agent' "${FOUNDRY_DEFAULT_AGENT:-claude}")"

    if ! agent_is_valid "$agent"; then
        log_error "Unknown agent type: $agent"
        log_error "Valid types: $(agent_valid_list)"
        return 1
    fi

    if foundry_agent_running "$box" "$root" "$agent"; then
        log_debug "Agent already running: $agent"
        return 0
    fi

    local session
    session="$(agent_session_name "$agent")"

    mkdir -p "${root}/logs"

    if agent_is_autonomous "$agent"; then
        # A goal-mode agent is driven by a forge event: the request supplies
        # the goal. Starting one from `foundry up` with nothing to work on
        # would launch a loop with no completion condition, which is the
        # expensive way to do nothing.
        if [[ "$agent" == *-goal && -z "${FOUNDRY_GOAL_CONDITION:-}" ]]; then
            log_warn "$(agent_display_name "$agent") runs from a forge event and has no task yet"
            log_warn "It starts when a watcher receives a request naming a mode."
            log_warn "For an interactive session instead, set .agent to 'claude'."
            return 0
        fi

        local script
        script="$(_agent_render_start_script "$root" "$agent")" || return 1

        log_info "Starting $(agent_display_name "$agent") in session '$session'"

        if ! sandbox_exec "$box" "$root" \
            tmux new-session -d -s "$session" "$script"; then
            log_error "Failed to start agent session '$session' in $box"
            log_error "Inspect it with: foundry shell $project"
            return 1
        fi
    else
        local binary
        binary="$(agent_binary "$agent")"

        log_info "Starting interactive $(agent_display_name "$agent") in session '$session'"

        # Through the wrapper: sbx's placeholder API key would otherwise
        # beat the account the user logged in with, and the CLI dies with
        # "Invalid API key" for a key nobody set.
        if ! sandbox_exec "$box" "$root" \
            tmux new-session -d -s "$session" \
            "/opt/foundry/run-agent.sh $binary"; then
            log_error "Failed to start agent session '$session' in $box"
            return 1
        fi
    fi

    # Verify it actually came up rather than reporting success blindly.
    if ! foundry_agent_running "$box" "$root" "$agent"; then
        log_error "Agent session '$session' exited immediately"
        local log_file
        log_file="$(agent_log_file "$agent" "$root")"
        if [[ -f "$log_file" ]]; then
            log_error "Last lines of ${log_file}:"
            tail -n 20 "$log_file" >&2
        fi
        return 1
    fi

    log_info "Agent running: $(agent_display_name "$agent")"
    return 0
}

# Stop the project's agent session.
# Usage: foundry_agent_stop <project> <box> <root>
foundry_agent_stop() {
    local project="$1"
    local box="$2"
    local root="$3"

    if ! sandbox_is_running "$box"; then
        log_debug "Sandbox not running, no agent to stop"
        return 0
    fi

    local agent session
    agent="$(project_get "$project" '.agent' "${FOUNDRY_DEFAULT_AGENT:-claude}")"
    session="$(agent_session_name "$agent")"

    if ! foundry_agent_running "$box" "$root" "$agent"; then
        log_debug "Agent not running: $agent"
        return 0
    fi

    log_info "Stopping agent session '$session'"

    if ! sandbox_exec "$box" "$root" tmux kill-session -t "$session"; then
        log_error "Failed to stop agent session '$session'"
        return 1
    fi

    return 0
}
