#!/usr/bin/env bash
#
# Agent Foundry - Workspace Management
#
# Functions for initializing and managing workspaces inside VMs.
# Workspaces contain repositories, context files, and agent memory.
#
# Workspace structure:
# /work/<project-name>/
# ├── PROMPT.md              # Ralph instructions
# ├── fix_plan.md            # Task list
# ├── workspace.json         # Configuration
# ├── README.md              # Project overview
# ├── repos/                 # Git repositories
# │   ├── backend/
# │   └── frontend/
# ├── context/               # AI context (read-only)
# │   ├── company.md
# │   ├── instructions.md
# │   ├── coding-standards.md
# │   └── architecture.md
# ├── memory/                # Agent memory (read-write)
# │   ├── decisions.md
# │   ├── progress.md
# │   ├── blockers.md
# │   └── learnings.md
# └── logs/                  # Agent logs
#

set -euo pipefail

# Source dependencies
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/utils.sh" ]]; then
    source "${SCRIPT_DIR}/utils.sh"
fi
if [[ -f "${SCRIPT_DIR}/registry.sh" ]]; then
    source "${SCRIPT_DIR}/registry.sh"
fi
if [[ -f "${SCRIPT_DIR}/vm.sh" ]]; then
    source "${SCRIPT_DIR}/vm.sh"
fi

# ============================================================================
# CONFIGURATION
# ============================================================================

# Workspace paths
WORKSPACE_BASE="/root"

# Template locations on host
FOUNDRY_BASE_DIR="${FOUNDRY_BASE_DIR:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
TEMPLATES_DIR="${FOUNDRY_BASE_DIR}/templates/workspace"

# SSH settings
FOUNDRY_SSH_USER="${FOUNDRY_SSH_USER:-root}"
FOUNDRY_SSH_OPTS="${FOUNDRY_SSH_OPTS:--o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o BatchMode=yes -o PasswordAuthentication=no}"

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

_get_vm_ip() {
    local vm_name="$1"
    registry_get "$vm_name" ".ip"
}

_get_vm_ssh_key() {
    local vm_name="$1"
    local ssh_key
    ssh_key=$(registry_get "$vm_name" ".ssh_key")
    if [[ "$ssh_key" == "null" ]]; then
        ssh_key=""
    fi
    echo "$ssh_key"
}

_ssh_cmd() {
    local vm_name="$1"
    shift

    local vm_ip ssh_key
    vm_ip=$(registry_get "$vm_name" ".ip")
    ssh_key=$(registry_get "$vm_name" ".ssh_key")

    # Remove quotes if present (jq output)
    ssh_key="${ssh_key%\"}"
    ssh_key="${ssh_key#\"}"

    # Use same quoting as vm_ssh for consistency (shell-escape arguments)
    local quoted_cmd
    printf -v quoted_cmd '%q ' "$@"

    # Use -n flag to prevent SSH from reading stdin (avoids password prompts and I/O deadlocks)
    # BatchMode=yes in FOUNDRY_SSH_OPTS ensures no interactive prompts
    if [[ -z "$ssh_key" || "$ssh_key" == "null" ]]; then
        # Fallback to default behavior if no key registered
        ssh -n $FOUNDRY_SSH_OPTS "${FOUNDRY_SSH_USER}@${vm_ip}" "bash -l -c ${quoted_cmd}"
    else
        ssh -n -i "$ssh_key" $FOUNDRY_SSH_OPTS "${FOUNDRY_SSH_USER}@${vm_ip}" "bash -l -c ${quoted_cmd}"
    fi
}

_scp_to_vm() {
    local vm_ip="$1"
    local ssh_key_path="$2"
    local source="$3"
    local dest="$4"
    scp ${ssh_key_path:+-i "$ssh_key_path"} $FOUNDRY_SSH_OPTS -r "$source" "${FOUNDRY_SSH_USER}@${vm_ip}:${dest}"
}

# Setup SSH keys for git repositories
_setup_ssh_keys() {
    local vm_name="$1"
    local project_dir="$2"
    local git_config="$3"

    log_info "Setting up SSH keys..."

    # Parse git-config.json to extract repos
    local repos_count
    repos_count=$(jq '.repositories | length' "$git_config")

    # Copy deploy keys and build SSH config
    local ssh_config_content="# Auto-generated by Agent Foundry\n\n"

    local i=0
    local -a copied_keys

    local vm_ip ssh_key_path
    vm_ip=$(_get_vm_ip "$vm_name")
    ssh_key_path=$(_get_vm_ssh_key "$vm_name")

    while [[ $i -lt $repos_count ]]; do
        local repo_name repo_url ssh_key
        repo_name=$(jq -r ".repositories[$i].name" "$git_config")
        repo_url=$(jq -r ".repositories[$i].url" "$git_config")
        ssh_key=$(jq -r ".repositories[$i].ssh_key" "$git_config")

        # Extract domain from URL (git@github.com:... -> github.com)
        local domain
        domain=$(echo "$repo_url" | sed -n 's/.*@\([^:]*\):.*/\1/p')

        # Copy key if not already copied
        if [[ ! " ${copied_keys[*]} " =~ \ ${ssh_key}\  ]]; then
            # Handle absolute vs relative paths
            local key_path
            if [[ "$ssh_key" == /* ]]; then
                # Absolute path - use as-is
                key_path="$ssh_key"
            else
                # Relative path - relative to project dir
                key_path="$project_dir/$ssh_key"
            fi

            if [[ ! -f "$key_path" ]]; then
                log_error "SSH key not found: $key_path"
                return 1
            fi

            # Use basename for the key filename in VM
            local vm_key_name
            vm_key_name="$(basename "$ssh_key")"

            # Copy private key to VM
            _scp_to_vm "$vm_ip" "$ssh_key_path" "$key_path" "/root/.ssh/$vm_key_name"
            _ssh_cmd "$vm_name" "chmod 600 /root/.ssh/$vm_key_name"

            copied_keys+=("$ssh_key")
            log_debug "Copied key: $key_path -> /root/.ssh/$vm_key_name"
        fi

        # Use basename for SSH config IdentityFile
        local vm_key_name
        vm_key_name="$(basename "$ssh_key")"

        # Add to SSH config
        ssh_config_content+="Host ${domain}-${repo_name}\n"
        ssh_config_content+="    HostName ${domain}\n"
        ssh_config_content+="    User git\n"
        ssh_config_content+="    IdentityFile ~/.ssh/${vm_key_name}\n"
        ssh_config_content+="    StrictHostKeyChecking no\n\n"

        i=$((i + 1))
    done

    # Write SSH config to VM (use temp file instead of heredoc since _ssh_cmd uses -n flag)
    local temp_config
    temp_config=$(mktemp)
    echo -e "$ssh_config_content" > "$temp_config"
    _scp_to_vm "$vm_ip" "$ssh_key_path" "$temp_config" "/root/.ssh/config"
    rm -f "$temp_config"
    _ssh_cmd "$vm_name" "chmod 600 /root/.ssh/config"

    log_info "SSH keys configured for $repos_count repositories"
}

# Copy project files (markdown and ralph folder) to VM workspace
_copy_project_files() {
    local vm_ip="$1"
    local ssh_key_path="$2"
    local workspace_path="$3"
    local project_dir="$4"

    log_info "Copying project files..."

    # Copy AGENT.md template
    local agent_template="${TEMPLATES_DIR}/../AGENT.md.template"
    if [[ -f "$agent_template" ]]; then
        _scp_to_vm "$vm_ip" "$ssh_key_path" "$agent_template" "${workspace_path}/AGENT.md"
        log_debug "Copied AGENT.md template"
    else
        log_warn "AGENT.md template not found: $agent_template"
    fi

    # Copy .ralphrc: prefer project-specific, fallback to template
    local project_ralphrc="$project_dir/.ralphrc"
    local ralphrc_template="${TEMPLATES_DIR}/../.ralphrc.template"

    if [[ -f "$project_ralphrc" ]]; then
        # Use project-specific .ralphrc (overrides default)
        _scp_to_vm "$vm_ip" "$ssh_key_path" "$project_ralphrc" "${workspace_path}/.ralphrc"
        log_debug "Copied project-specific .ralphrc"
    elif [[ -f "$ralphrc_template" ]]; then
        # Use default template as fallback
        _scp_to_vm "$vm_ip" "$ssh_key_path" "$ralphrc_template" "${workspace_path}/.ralphrc"
        log_debug "Copied default .ralphrc template (full tool access for autonomous VM)"
    fi

    # Copy .ralph/ folder if exists
    if [[ -d "$project_dir/.ralph" ]]; then
        log_debug "Copying .ralph/ folder..."
        _ssh_cmd "$vm_ip" "$ssh_key_path" "mkdir -p '${workspace_path}/.ralph'"
        _scp_to_vm "$vm_ip" "$ssh_key_path" "$project_dir/.ralph/." "${workspace_path}/.ralph/"
    fi

    # Copy all .md files to context/ (excluding .ralph/)
    local md_files
    md_files=$(find "$project_dir" -maxdepth 1 -name "*.md" -type f)

    if [[ -n "$md_files" ]]; then
        log_debug "Copying .md files to context/..."
        while IFS= read -r md_file; do
            if [[ -f "$md_file" ]]; then
                local filename
                filename=$(basename "$md_file")
                _scp_to_vm "$vm_ip" "$ssh_key_path" "$md_file" "${workspace_path}/context/${filename}"
            fi
        done <<< "$md_files"
    fi
}

_check_vm_running() {
    local vm_name="$1"
    local status
    status=$(registry_get "$vm_name" ".status" 2>/dev/null)
    if [[ "$status" != "running" ]]; then
        log_error "VM '$vm_name' is not running (status: ${status:-unknown})"
        return 1
    fi
    return 0
}

_validate_config_file() {
    local config_file="$1"

    if [[ ! -f "$config_file" ]]; then
        log_error "Config file not found: $config_file"
        return 1
    fi

    # Validate JSON
    if ! jq empty "$config_file" 2>/dev/null; then
        log_error "Invalid JSON in config file: $config_file"
        return 1
    fi

    # Check for repositories array
    local repos_count
    repos_count=$(jq '.repositories | length' "$config_file" 2>/dev/null)
    if [[ -z "$repos_count" || "$repos_count" == "null" ]]; then
        log_error "Config missing 'repositories' array in file: $config_file"
        return 1
    fi

    return 0
}

# ============================================================================
# WORKSPACE INITIALIZATION
# ============================================================================

_resolve_project_dir() {
    local vm_name="$1"
    local project_ref="${2:-}"

    # Use actual user's home, not root's home when running with doas/sudo.
    local host_home
    host_home="$(resolve_host_home)"
    local config_projects_dir="${XDG_CONFIG_HOME:-${host_home}/.config}/foundry/projects"
    local bundled_projects_dir="${FOUNDRY_BASE_DIR}/projects"

    local project_dir=""

    # 1) Explicit reference from CLI.
    if [[ -n "$project_ref" ]]; then
        if [[ -f "$project_ref" ]]; then
            # Support passing git-config.json path directly.
            project_dir="$(dirname "$project_ref")"
        elif [[ -d "$project_ref" ]]; then
            # Support passing absolute/relative project directory.
            project_dir="$project_ref"
        elif [[ -d "$config_projects_dir/$project_ref" ]]; then
            # Support passing project name.
            project_dir="$config_projects_dir/$project_ref"
        elif [[ -d "$bundled_projects_dir/$project_ref" ]]; then
            project_dir="$bundled_projects_dir/$project_ref"
        fi
    fi

    # 2) Persisted project directory in VM registry metadata.
    if [[ -z "$project_dir" ]]; then
        local stored_project_dir
        stored_project_dir=$(registry_get "$vm_name" ".project_dir" 2>/dev/null || true)
        if [[ -n "$stored_project_dir" && "$stored_project_dir" != "null" && -d "$stored_project_dir" ]]; then
            project_dir="$stored_project_dir"
        fi
    fi

    # 3) Persisted project name in VM registry metadata.
    if [[ -z "$project_dir" ]]; then
        local stored_project_name
        stored_project_name=$(registry_get "$vm_name" ".project_name" 2>/dev/null || true)
        if [[ -n "$stored_project_name" && "$stored_project_name" != "null" ]]; then
            if [[ -d "$config_projects_dir/$stored_project_name" ]]; then
                project_dir="$config_projects_dir/$stored_project_name"
            elif [[ -d "$bundled_projects_dir/$stored_project_name" ]]; then
                project_dir="$bundled_projects_dir/$stored_project_name"
            fi
        fi
    fi

    # 4) Fallback: infer from VM name.
    if [[ -z "$project_dir" ]]; then
        if [[ -d "$config_projects_dir/$vm_name" ]]; then
            project_dir="$config_projects_dir/$vm_name"
        elif [[ -d "$bundled_projects_dir/$vm_name" ]]; then
            project_dir="$bundled_projects_dir/$vm_name"
        fi
    fi

    if [[ -z "$project_dir" ]]; then
        log_error "Could not resolve project directory."
        log_error "Tried explicit input, VM metadata, and name-based lookup."
        log_error "Provide a project path/name explicitly: foundry workspace sync <vm> <project|path>"
        return 1
    fi

    if [[ ! -f "$project_dir/git-config.json" ]]; then
        log_error "Project missing git-config.json: $project_dir"
        return 1
    fi

    if [[ ! -f "$project_dir/agents.json" ]]; then
        log_error "Project missing agents.json: $project_dir"
        return 1
    fi

    echo "$project_dir"
}

# Initialize workspace in VM from config file
# Usage: workspace_init <vm_name> <config_file>
#
# Config file format (JSON):
# {
#   "name": "project-name",
#   "repositories": [
#     {"name": "backend", "url": "git@github.com:org/backend.git", "branch": "main"},
#     {"name": "frontend", "url": "git@github.com:org/frontend.git"}
#   ],
#   "agent": {
#     "default_cli": "claude",
#     "context_files": ["company.md", "instructions.md"]
#   }
# }
workspace_init() {
    local vm_name="$1"
    local config_file="$2"

    if [[ -z "$vm_name" ]]; then
        log_error "VM name required"
        return 1
    fi

    if [[ -z "$config_file" ]]; then
        log_error "Config file required"
        return 1
    fi

    _check_vm_running "$vm_name" || return 1
    _validate_config_file "$config_file" || return 1

    local vm_ip ssh_key_path
    vm_ip=$(_get_vm_ip "$vm_name")
    ssh_key_path=$(_get_vm_ssh_key "$vm_name")

    # Workspace path is /root/ (no subdirectories)
    local workspace_path="$WORKSPACE_BASE"

    # Derive project dir from config file path
    local project_dir
    project_dir="$(dirname "$config_file")"

    log_info "Initializing workspace in VM '$vm_name' at $workspace_path..."

    # Check for required agents.json
    local agents_config="$project_dir/agents.json"
    if [[ ! -f "$agents_config" ]]; then
        log_error "agents.json not found: $agents_config"
        log_error "See example: projects/example-project/agents.json"
        return 1
    fi

    # Parse and validate agents.json
    local agents_list
    agents_list=$(jq -r '.agents[]' "$agents_config" 2>/dev/null)
    if [[ $? -ne 0 || -z "$agents_list" ]]; then
        log_error "Invalid or empty agents.json: $agents_config"
        return 1
    fi

    # Validate agent types
    local supported_agents=("frankbria/ralph-claude-code" "@anthropic-ai/claude-code" "@openai/codex" "@google/gemini-cli")
    while IFS= read -r agent; do
        local supported=false
        for valid in "${supported_agents[@]}"; do
            if [[ "$agent" == "$valid" ]]; then
                supported=true
                break
            fi
        done
        if [[ "$supported" == "false" ]]; then
            log_error "Unsupported agent in agents.json: $agent"
            log_error "Supported: ${supported_agents[*]}"
        fi
    done <<< "$agents_list"

    # Create workspace directory structure
    log_debug "Creating workspace directories in /root/..."
    _ssh_cmd "$vm_name" "mkdir -p '$workspace_path/repos'"

    # Set up SSH keys for git access
    _setup_ssh_keys "$vm_name" "$project_dir" "$config_file"

    # Clone repositories
    _clone_repositories "$vm_name" "$workspace_path" "$config_file"

    # Copy agent dotfolders
    log_info "Copying agent configurations..."
    while IFS= read -r agent; do
        local dotfolder=""
        case "$agent" in
            "frankbria/ralph-claude-code")
                dotfolder=".ralph"
                ;;
            "@anthropic-ai/claude-code")
                dotfolder=".claude"
                ;;
            "@openai/codex")
                dotfolder=".codex"
                ;;
            "@google/gemini-cli")
                dotfolder=".gemini"
                ;;
        esac

        if [[ -n "$dotfolder" && -d "$project_dir/$dotfolder" ]]; then
            log_debug "Copying $dotfolder/ to VM..."
            _scp_to_vm "$vm_ip" "$ssh_key_path" "$project_dir/$dotfolder" "$workspace_path/"
        fi
    done <<< "$agents_list"

    # Copy all .md files from project dir to /root/
    log_info "Copying markdown files..."
    local md_files
    md_files=$(find "$project_dir" -maxdepth 1 -name "*.md" -type f 2>/dev/null)
    if [[ -n "$md_files" ]]; then
        while IFS= read -r md_file; do
            local filename
            filename=$(basename "$md_file")
            _scp_to_vm "$vm_ip" "$ssh_key_path" "$md_file" "$workspace_path/$filename"
            log_debug "Copied $filename"
        done <<< "$md_files"
    fi

    # Ralph uses files in .ralph/ folder (already copied above)
    # No additional Ralph initialization needed

    # Update registry with workspace info
    registry_update "$vm_name" ".workspace" "\"$vm_name\""

    log_info "Workspace initialized: $workspace_path"
    log_info "Agents configured from agents.json"
    log_info ""
    log_info "Note: Login to agents (claude/codex/gemini) via SSH if not using API tokens"
    log_info "      SSH into VM: foundry vm ssh $vm_name"
    log_info ""
    log_info "Next steps:"
    log_info "  1. Start coding in /root/repos/"
    log_info "  2. Edit PROMPT.md or other context files as needed"

    return 0
}

# Sync project configuration and agent dotfiles into an existing VM workspace.
# This updates mutable workspace files without recloning repositories.
# Usage: workspace_sync <vm_name> [project_name|project_dir|git-config.json]
workspace_sync() {
    local vm_name="${1:-}"
    local project_ref="${2:-}"

    if [[ -z "$vm_name" ]]; then
        log_error "VM name required"
        log_error "Usage: foundry workspace sync <vm> [project|path]"
        return 1
    fi

    _check_vm_running "$vm_name" || return 1

    local project_dir
    project_dir=$(_resolve_project_dir "$vm_name" "$project_ref") || return 1

    local vm_ip ssh_key_path
    vm_ip=$(_get_vm_ip "$vm_name")
    ssh_key_path=$(_get_vm_ssh_key "$vm_name")

    local workspace_path="$WORKSPACE_BASE"

    log_info "Syncing workspace files to VM '$vm_name' from: $project_dir"

    # Ensure workspace exists before syncing.
    if ! _ssh_cmd "$vm_name" "test -d '$workspace_path'"; then
        log_error "Workspace path does not exist in VM: $workspace_path"
        log_error "Initialize first: foundry workspace init $vm_name $project_dir/git-config.json"
        return 1
    fi

    # Sync agent dotfolders for known agent integrations.
    local -a dotfolders=(".ralph" ".claude" ".codex" ".gemini")
    local dotfolder
    for dotfolder in "${dotfolders[@]}"; do
        if [[ -d "$project_dir/$dotfolder" ]]; then
            log_info "Syncing $dotfolder/"
            _ssh_cmd "$vm_name" "mkdir -p '$workspace_path/$dotfolder'"
            _scp_to_vm "$vm_ip" "$ssh_key_path" "$project_dir/$dotfolder/." "$workspace_path/$dotfolder/"
            # Remove editor temp/swap files after sync.
            _ssh_cmd "$vm_name" "find '$workspace_path/$dotfolder' -type f \
                \\( -name '*.swp' -o -name '*.swo' -o -name '*.swn' -o -name '*.kate-swp' -o -name '*~' -o -name '.#*' -o -name '#*#' \\) \
                -delete"
        fi
    done

    # Sync common agent config files when present.
    local -a config_files=(".ralphrc")
    local config_file
    for config_file in "${config_files[@]}"; do
        if [[ -f "$project_dir/$config_file" ]]; then
            log_info "Syncing $config_file"
            _scp_to_vm "$vm_ip" "$ssh_key_path" "$project_dir/$config_file" "$workspace_path/$config_file"
        fi
    done

    # Sync top-level markdown context/docs files.
    local md_files
    md_files=$(find "$project_dir" -maxdepth 1 -name "*.md" -type f 2>/dev/null || true)
    if [[ -n "$md_files" ]]; then
        log_info "Syncing markdown files"
        while IFS= read -r md_file; do
            local filename
            filename=$(basename "$md_file")
            _scp_to_vm "$vm_ip" "$ssh_key_path" "$md_file" "$workspace_path/$filename"
        done <<< "$md_files"
    fi

    # Refresh metadata for future sync auto-detection.
    registry_update "$vm_name" ".project_dir" "\"$project_dir\""
    registry_update "$vm_name" ".project_name" "\"$(basename "$project_dir")\""

    log_info "Workspace sync complete."
    log_info "Updated: dotfolders (.ralph/.claude/.codex/.gemini), .ralphrc, and top-level *.md files."

    return 0
}

# Clone repositories specified in config
_clone_repositories() {
    local vm_name="$1"
    local workspace_path="$2"
    local config_file="$3"

    local repos_count
    repos_count=$(jq '.repositories | length' "$config_file")

    if [[ "$repos_count" -eq 0 ]]; then
        log_debug "No repositories to clone"
        return 0
    fi

    log_info "Cloning $repos_count repositories..."

    local i=0
    while [[ $i -lt $repos_count ]]; do
        local repo_name repo_url repo_branch
        repo_name=$(jq -r ".repositories[$i].name" "$config_file")
        repo_url=$(jq -r ".repositories[$i].url" "$config_file")
        repo_branch=$(jq -r ".repositories[$i].branch // \"main\"" "$config_file")

        # Extract domain and rewrite URL to use SSH config host
        # git@github.com:org/repo.git -> git@github.com-reponame:org/repo.git
        local domain modified_url
        domain=$(echo "$repo_url" | sed -n 's/.*@\([^:]*\):.*/\1/p')
        if [[ -n "$domain" ]]; then
            # Rewrite URL to use the SSH config host alias
            modified_url="${repo_url/@${domain}:/@${domain}-${repo_name}:}"
        else
            # Not an SSH URL, use as-is
            modified_url="$repo_url"
        fi

        log_debug "Cloning $repo_name from $modified_url (branch: $repo_branch)..."

        _ssh_cmd "$vm_name" "cd '${workspace_path}/repos' && \
            git clone --branch '$repo_branch' '$modified_url' '$repo_name' 2>&1" || {
            log_warn "Failed to clone $repo_name"
            return 1
        }

        i=$((i + 1))
    done
}

# Copy context files from templates
_copy_context_files() {
    local vm_name="$1"
    local workspace_path="$2"
    local config_file="$3"

    log_debug "Copying context file templates..."

    # Copy all context templates
    local context_files=("company.md" "instructions.md" "coding-standards.md" "architecture.md")

    for file in "${context_files[@]}"; do
        local template="${TEMPLATES_DIR}/context/${file}.example"
        if [[ -f "$template" ]]; then
            local vm_ip ssh_key_path
            vm_ip=$(_get_vm_ip "$vm_name")
            ssh_key_path=$(_get_vm_ssh_key "$vm_name")
            _scp_to_vm "$vm_ip" "$ssh_key_path" "$template" "${workspace_path}/context/${file}"
            log_debug "Copied $file"
        else
            # Create placeholder if template doesn't exist
            _ssh_cmd "$vm_name" "echo '# ${file%.md}' > '${workspace_path}/context/${file}'"
            _ssh_cmd "$vm_name" "echo '' >> '${workspace_path}/context/${file}'"
            _ssh_cmd "$vm_name" "echo 'TODO: Add content for ${file}' >> '${workspace_path}/context/${file}'"
        fi
    done
}

# Initialize memory files
_init_memory_files() {
    local vm_name="$1"
    local workspace_path="$2"
    local project_name="$3"

    log_debug "Initializing memory files..."

    local timestamp
    timestamp=$(date -Iseconds)

    # decisions.md
    _ssh_cmd "$vm_name" "cat > '${workspace_path}/memory/decisions.md'" << EOF
# Design Decisions

Track important technical decisions made during development.

## Format

### [Date] Decision Title
- **Context**: Why this decision was needed
- **Decision**: What was decided
- **Consequences**: What this means going forward

---

*Initialized: $timestamp*
EOF

    # progress.md
    _ssh_cmd "$vm_name" "cat > '${workspace_path}/memory/progress.md'" << EOF
# Work Progress

Track completed work and milestones.

## Current Sprint

### In Progress
- [ ] ...

### Completed
- [x] Workspace initialized ($timestamp)

---

*Last updated: $timestamp*
EOF

    # blockers.md
    _ssh_cmd "$vm_name" "cat > '${workspace_path}/memory/blockers.md'" << EOF
# Current Blockers

Track issues blocking progress and their resolution.

## Active Blockers

*None currently*

## Resolved Blockers

---

*Last updated: $timestamp*
EOF

    # learnings.md
    _ssh_cmd "$vm_name" "cat > '${workspace_path}/memory/learnings.md'" << EOF
# Patterns & Learnings

Track patterns discovered and lessons learned about this codebase.

## Codebase Patterns

*Discover patterns as you work*

## Common Pitfalls

*Document issues to avoid*

---

*Initialized: $timestamp*
EOF
}

# ============================================================================
# RALPH INITIALIZATION
# ============================================================================

# Initialize Ralph structure in workspace
# Usage: workspace_init_ralph <vm_name>
workspace_init_ralph() {
    local vm_name="$1"

    if [[ -z "$vm_name" ]]; then
        log_error "VM name required"
        return 1
    fi

    _check_vm_running "$vm_name" || return 1

    local vm_ip ssh_key_path workspace_name workspace_path
    vm_ip=$(_get_vm_ip "$vm_name")
    ssh_key_path=$(_get_vm_ssh_key "$vm_name")
    workspace_name=$(registry_get "$vm_name" ".workspace" 2>/dev/null)

    if [[ -z "$workspace_name" || "$workspace_name" == "null" ]]; then
        workspace_name="$vm_name"
    fi

    workspace_path="${WORKSPACE_BASE}"

    log_info "Initializing Ralph in workspace '$workspace_name'..."

    # Check if Ralph configuration exists
    if ! _ssh_cmd "$vm_name" "test -d '$workspace_path/.ralph'"; then
        log_error "Ralph configuration not found in $workspace_path/.ralph"
        log_info "Initialize workspace first with: foundry workspace init $vm_name <config.json>"
        return 1
    fi

    # Ensure logs directory exists
    _ssh_cmd "$vm_name" "mkdir -p '${workspace_path}/logs'"

    # Check if Ralph is installed
    if _ssh_cmd "$vm_name" "command -v ralph >/dev/null 2>&1"; then
        log_info "Ralph is installed and ready"
    else
        log_warn "Ralph binary not found in VM PATH."
        log_warn "Ensure the VM image has Ralph installed."
    fi

    log_info "Ralph initialization verified"
    return 0
}

# ============================================================================
# WORKSPACE EDITING
# ============================================================================

# Edit a workspace file via SSH
# Usage: workspace_edit <vm_name> <file>
workspace_edit() {
    local vm_name="$1"
    local file="$2"

    if [[ -z "$vm_name" ]]; then
        log_error "VM name required"
        return 1
    fi

    if [[ -z "$file" ]]; then
        log_error "File path required"
        return 1
    fi

    _check_vm_running "$vm_name" || return 1

    local vm_ip ssh_key_path workspace_name workspace_path
    vm_ip=$(_get_vm_ip "$vm_name")
    ssh_key_path=$(_get_vm_ssh_key "$vm_name")
    workspace_name=$(registry_get "$vm_name" ".workspace" 2>/dev/null)

    if [[ -z "$workspace_name" || "$workspace_name" == "null" ]]; then
        workspace_name="$vm_name"
    fi

    workspace_path="${WORKSPACE_BASE}"

    # Determine full path
    local full_path
    if [[ "$file" == /* ]]; then
        full_path="$file"
    else
        full_path="${workspace_path}/${file}"
    fi

    # Check if file exists
    if ! _ssh_cmd "$vm_name" "test -f '$full_path'"; then
        log_warn "File does not exist: $full_path"
        if confirm "Create new file?"; then
            _ssh_cmd "$vm_name" "touch '$full_path'"
        else
            return 1
        fi
    fi

    log_info "Opening $full_path in editor..."

    # Determine editor
    local editor="${EDITOR:-vim}"

    # Open SSH connection with editor
    exec ssh -t ${ssh_key_path:+-i "$ssh_key_path"} $FOUNDRY_SSH_OPTS "${FOUNDRY_SSH_USER}@${vm_ip}" "$editor '$full_path'"
}

# ============================================================================
# WORKSPACE INFO
# ============================================================================

# Show workspace information
# Usage: workspace_info <vm_name>
workspace_info() {
    local vm_name="$1"

    if [[ -z "$vm_name" ]]; then
        log_error "VM name required"
        return 1
    fi

    _check_vm_running "$vm_name" || return 1

    local vm_ip ssh_key_path workspace_name workspace_path
    vm_ip=$(_get_vm_ip "$vm_name")
    ssh_key_path=$(_get_vm_ssh_key "$vm_name")
    workspace_name=$(registry_get "$vm_name" ".workspace" 2>/dev/null)

    if [[ -z "$workspace_name" || "$workspace_name" == "null" ]]; then
        workspace_name="$vm_name"
    fi

    workspace_path="${WORKSPACE_BASE}"

    echo "Workspace: $workspace_name"
    echo "Path: $workspace_path"
    echo "VM: $vm_name ($vm_ip)"
    echo ""

    # Check if workspace exists
    if ! _ssh_cmd "$vm_name" "test -d '$workspace_path'"; then
        echo "Status: NOT INITIALIZED"
        echo ""
        echo "Initialize with: foundry workspace init $vm_name <config.json>"
        return 0
    fi

    echo "Status: Initialized"
    echo ""

    # Show workspace.json if exists
    if _ssh_cmd "$vm_name" "test -f '${workspace_path}/workspace.json'"; then
        echo "=== Configuration ==="
        _ssh_cmd "$vm_name" "jq '.' '${workspace_path}/workspace.json' 2>/dev/null" || \
            _ssh_cmd "$vm_name" "cat '${workspace_path}/workspace.json'"
        echo ""
    fi

    # Show repositories
    echo "=== Repositories ==="
    _ssh_cmd "$vm_name" "ls -1 '${workspace_path}/repos/' 2>/dev/null" | \
        while read -r repo; do
            echo "  $repo"
        done
    echo ""

    # Show context files
    echo "=== Context Files ==="
    _ssh_cmd "$vm_name" "ls -1 '${workspace_path}/context/' 2>/dev/null" | \
        while read -r file; do
            echo "  $file"
        done
    echo ""

    # Show disk usage
    echo "=== Disk Usage ==="
    _ssh_cmd "$vm_name" "du -sh '${workspace_path}' 2>/dev/null" || echo "  Unknown"

    return 0
}

# ============================================================================
# WORKSPACE TEMPLATES
# ============================================================================

# Create a workspace config template
# Usage: workspace_template <output_file>
workspace_template() {
    local output_file="${1:-workspace.json}"

    log_info "Creating workspace config template: $output_file"

    cat > "$output_file" << 'EOF'
{
  "name": "my-project",
  "description": "Project description here",
  "repositories": [
    {
      "name": "backend",
      "url": "git@github.com:myorg/backend.git",
      "branch": "main"
    },
    {
      "name": "frontend",
      "url": "git@github.com:myorg/frontend.git",
      "branch": "main"
    }
  ],
  "agent": {
    "default_cli": "claude",
    "auto_start": false,
    "context_files": [
      "company.md",
      "instructions.md",
      "coding-standards.md",
      "architecture.md"
    ]
  },
  "settings": {
    "git_user_name": "AI Agent",
    "git_user_email": "agent@example.com"
  }
}
EOF

    log_info "Template created. Edit and use with: foundry workspace init <vm> $output_file"
    return 0
}

# ============================================================================
# TESTING/EXAMPLES
# ============================================================================
#
# Example workflow:
#
#   # Create config template
#   workspace_template my-project.json
#
#   # Edit configuration
#   vim my-project.json
#
#   # Initialize workspace in VM
#   workspace_init my-project my-project.json
#
#   # Initialize Ralph
#   workspace_init_ralph my-project
#
#   # Edit files
#   workspace_edit my-project PROMPT.md
#   workspace_edit my-project context/instructions.md
#
#   # Show workspace info
#   workspace_info my-project
#
#   # Start agent
#   foundry agent start my-project ralph
#
